#  RootShield Client
#  Author: @ImKKingshuk

CC = gcc
CFLAGS = -Wall -Werror

all: rootshield_client

rootshield_client: rootshield_client.c
	$(CC) $(CFLAGS) -o rootshield_client rootshield_client.c

clean:
	rm -f rootshield_client